# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
# spec:
#   strategy:
#     type: Recreate
#   selector:
#     matchLabels:
#       app: nginx
#   replicas: 1
#   template: 
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx
#         ports:
#         - containerPort: 80
#         volumeMounts:
#           - name: html-file
#             mountPath: /usr/share/nginx/html
#       volumes:  
#         - name: html-file 
#           configMap:  
#             name: nginx-index-v1
# --- 
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
#   labels:
#     app: nginx
# spec:
#   type: NodePort
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 80
#     nodePort: 30080
#   selector:
#     app: nginx
# ---
# kind: ConfigMap  
# apiVersion: v1  
# metadata:  
#   name: nginx-index-v1
# data:  
#   index.html: Nginx V1
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-nginx 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: nginx 
        image: nginx:1.18.0
        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume 
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config-volume 
        configMap:
          name: nginx-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |-
    server {
      listen     8080;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
Events:  <none>


